import { Habit } from './types';

export const SAMPLE_HABITS: Habit[] = [
    {
        id: '1',
        name: 'Morning Workout',
        icon: '🏋️',
        color: '#FF6B6B',
        category: 'health',
        streak: 5,
        completedToday: false,
        description: 'Start your day with 30 minutes of exercise',
        completedDates: [],
    },
    {
        id: '2',
        name: 'Read 30 Minutes',
        icon: '📚',
        color: '#4ECDC4',
        category: 'learning',
        streak: 12,
        completedToday: true,
        description: 'Read books to expand your knowledge',
        completedDates: [],
    },
    {
        id: '3',
        name: 'Meditation',
        icon: '🧘',
        color: '#95E1D3',
        category: 'mindfulness',
        streak: 3,
        completedToday: false,
        description: '10 minutes of mindfulness meditation',
        completedDates: [],
    },
    {
        id: '4',
        name: 'Drink Water',
        icon: '💧',
        color: '#38B6FF',
        category: 'health',
        streak: 8,
        completedToday: true,
        description: 'Drink 8 glasses of water daily',
        completedDates: [],
    },
    {
        id: '5',
        name: 'Healthy Breakfast',
        icon: '🥗',
        color: '#FFE66D',
        category: 'health',
        streak: 15,
        completedToday: true,
        description: 'Eat a nutritious breakfast',
        completedDates: [],
    },
    {
        id: '6',
        name: 'Journal Writing',
        icon: '✍️',
        color: '#A8E6CF',
        category: 'mindfulness',
        streak: 7,
        completedToday: false,
        description: 'Write down your thoughts and feelings',
        completedDates: [],
    },
    {
        id: '7',
        name: 'Learn New Skill',
        icon: '🎯',
        color: '#FF8B94',
        category: 'learning',
        streak: 4,
        completedToday: false,
        description: 'Spend time learning something new',
        completedDates: [],
    },
    {
        id: '8',
        name: 'Evening Walk',
        icon: '🚶',
        color: '#C7CEEA',
        category: 'health',
        streak: 10,
        completedToday: false,
        description: 'Take a relaxing walk in the evening',
        completedDates: [],
    },
    {
        id: '9',
        name: 'Practice Gratitude',
        icon: '🙏',
        color: '#FFDAC1',
        category: 'mindfulness',
        streak: 6,
        completedToday: false,
        description: 'List 3 things you\'re grateful for',
        completedDates: [],
    },
    {
        id: '10',
        name: 'Code Practice',
        icon: '💻',
        color: '#B4A7D6',
        category: 'productivity',
        streak: 9,
        completedToday: false,
        description: 'Practice coding for 1 hour',
        completedDates: [],
    },
    {
        id: '11',
        name: 'Yoga Session',
        icon: '🤸',
        color: '#FFB6B9',
        category: 'health',
        streak: 2,
        completedToday: false,
        description: '20 minutes of yoga practice',
        completedDates: [],
    },
    {
        id: '12',
        name: 'Call Family',
        icon: '📞',
        color: '#FEC8D8',
        category: 'social',
        streak: 11,
        completedToday: false,
        description: 'Stay connected with loved ones',
        completedDates: [],
    },
];

export const HABIT_CATEGORIES = [
    { id: 'health', name: 'Health', icon: '💪', color: '#FF6B6B' },
    { id: 'productivity', name: 'Productivity', icon: '⚡', color: '#4ECDC4' },
    { id: 'mindfulness', name: 'Mindfulness', icon: '🧘', color: '#95E1D3' },
    { id: 'social', name: 'Social', icon: '👥', color: '#FFE66D' },
    { id: 'learning', name: 'Learning', icon: '📚', color: '#A8E6CF' },
];
